version: '3'
services: 
  server:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - /root/GCPConfig/:/root/GCPConfig
    depends_on:
      - redis
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - EMAIL=my_email@gmail.com
      - PASSWORD=somepassword
    links:
      - redis
    command: npm run start

  redis:
    image: redis:alpine
    volumes:
      - /root/redis-data:/data

    
