version: '3'
services: 
  server:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - /root/GCPConfig/:/root/GCPConfig
    depends_on:
      - redis
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - EMAIL=my_email@gmail.com
      - PASSWORD=somepassword
      - GOOGLE_APPLICATION_CREDENTIALS=/root/GCPConfig/GCPCredential.json
    links:
      - redis
    command: npm run start
  
  consumer:
    build: ./consumer
    volumes:
      - /root/GCPConfig/:/root/GCPConfig
    depends_on:
      - server
    environment:
      - NODE_ENV=development
      - SOCKET_ADDR=server
      - SOCKET_PORT=3001
      - GOOGLE_APPLICATION_CREDENTIALS=/root/GCPConfig/GCPCredential.json
    links:
      - server
    command: npm run start

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - /root/redis-data:/data

    
