version: '3'
  server:
    build: 
      context: .
      dockerfile: ./backend
    ports:
      - "3001:3001"
    volumes:
      - './backend:/home/node'
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - EMAIL=myemail@gmail.com
      - PASSWORD=mypass
      - NODE_ENV=development
    command: ['npm', 'run', 'start']

  redis:
    image: redis:alpine

    
